drop table if exists [dbo].[EmplDetail] 
CREATE TABLE [dbo].[EmplDetail] (
    [EmpId] float,
    [First Name] nvarchar(255),
    [Last Name] nvarchar(255),
    [Τύπος σύμβασης] float,
    [Department name] nvarchar(255),
    [Περιγραφή] nvarchar(255),
    [ΣΧΕΣΗ ΕΡΓΑΣΙΑΣ (Status)] nvarchar(255),
    [Περιγραφή Πινακοποιημένου Πεδίου_4] nvarchar(255),
    [Περιγραφή Πινακοποιημένου Πεδίου_5] nvarchar(255),
    [Ονομαστικός μισθός bf] float,
    [Salary Adjustment factor] float,
    [FTEs] float,
    [Department Change Date] datetime,
    [Level] nvarchar(255),
    [Position Level] nvarchar(255),
    [Job Position] nvarchar(255),
    [Dept Name] nvarchar(255),
    [Part-time flag] float,
    [Hire Date] datetime,
    [initial_Salary_1] float,
    [BudgetMonth] datetime,
    [Initial Salary] float,
    [Check hire date for new hires] nvarchar(255),
    [Grade - Rank] float,
    [Growth_by_Grade-Rank#Salary % Growth] datetime,
    [Growth_by_Month#Salary % Growth] float,
    [CountrySpecific_salary_Growth#Salary % Growth] nvarchar(255),
    [BudgetMonth_ID] float,
    [Medical cost monthly x 12] nvarchar(50),
    [Pension Adj] float,
    [Monthly Mobile Allowance] nvarchar(255),
    [Μίσθωμα Εταιρικού Αυτοκινήτου βάση Πολιτικής] nvarchar(255),
    [Ποσό Δωροκάρτας New Year βάση Πολιτικής] nvarchar(255),
    [SalaryGrowthSwitch] nvarchar(255),
    [LiveGrowthSwitch] nvarchar(50),
    [EmpID+MonthID] nvarchar(255),
    [Contract] nvarchar(255),
    [Contractual Paid Hrs] float,
    [No of Working days] float,
    [hrspercontract#hours] float,
    [Working Hrs] float,
    [% of sickness] float,
    [% of Absenteeism] nvarchar(255),
    [Division] nvarchar(255),
    [OnOff_staff_dateperiod#CHECK] nvarchar(255),
    [OnOff_staff_dateperiod#Month OFF] nvarchar(255),
    [ONOFF_flag] nvarchar(255),
    [OnOff_staff_reporting#Month OFF] nvarchar(255),
    [Off_flag_reporting] nvarchar(255),
    [Month no] float,
    [Month full] nvarchar(255),
    [BudgetMonth (Month Index)] float,
    [BudgetMonth (Month)] nvarchar(255)
)